/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ingrid' at '3/28/17 9:40 PM' with Gradle 2.14.1
 *
 * @author Ingrid, @date 3/28/17 9:40 PM
 */
public class Library {
    public boolean someLibraryMethod()
    {
        return true;
        //library method
    }
}
